Update polkadot-v0.9.29
integritee-network/parachain pull request #168
Opened 2022-10-07 12:40 UTC by OverOrion

2022-10-20 12:26 UTC, haerdib approved these changes

2022-10-20 12:29 UTC, haerdib commented
Ah, sorry, I forgot to check for the scripts: Can you update the launch scripts (e.g. zombienet and polkadot-launch) to v0.9.29 as well? Can be easily done via search and replace.

2022-10-24 07:19 UTC, clangenb approved these changes
No, it is fine for me, we should only test the runtime upgrade, when we actually perform one.

2022-10-24 07:23 UTC, clangenb requested changes
One minor issue. Please bump the spec version of the shell-runtime as well. :)

2022-10-26 06:09 UTC, clangenb reviewed
Also bump the shell-runtime `spec_version` here please: https://github.com/integritee-network/parachain/blob/53ba430bff5797760b21b064b7d6f925fdbef2a5/polkadot-parachains/shell-runtime/src/lib.rs#L79

2022-10-26 06:49 UTC, clangenb approved these changes
Nice, looks good to me!

2022-10-26 06:49 UTC, clangenb commented on zombienet/launch-rococo-local-with-integritee-xcm.toml
> -#this is not working !!!
🥳

2022-10-26 07:27 UTC, merged